let aux = "";

for(let i=0;i<500;i++)
{
    aux+="./test.sh; ";
}

console.log(aux);

// ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; .t 
// est.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; 
// ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; 
// ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; 
// ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh; ./test.sh;